# Generated by Django 2.0.7 on 2018-07-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=5, verbose_name='教师姓名')),
                ('tPhone', models.CharField(max_length=11, verbose_name='联系电话')),
            ],
        ),
    ]
