# Generated by Django 2.0.7 on 2018-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userNum', models.IntegerField(default=0)),
                ('userPhone', models.IntegerField(default=0)),
            ],
        ),
    ]
