# Generated by Django 2.0.7 on 2018-07-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('user', '0002_auto_20180726_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eKind', models.CharField(choices=[('请选择设备类型：', '请选择设备类型'), ('', ''), ('', ''), ('', ''), ('', '')], default='请选择设备类型', max_length=10, verbose_name='设备类型')),
                ('eName', models.CharField(max_length=10, verbose_name='设备名称')),
                ('eRoom', models.CharField(max_length=10, verbose_name='设备所在教室')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usecount',
            field=models.IntegerField(default=0, verbose_name='已借数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=11, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userNum',
            field=models.CharField(max_length=15, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=11, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPwd',
            field=models.CharField(max_length=78, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='借用学生'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='负责教师'),
        ),
    ]
