# Generated by Django 2.0.7 on 2018-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180727_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eState',
            field=models.CharField(default='可借', max_length=3, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eKind',
            field=models.CharField(choices=[('请选择设备类型：', '请选择设备类型'), ('计算机类', '计算机类'), ('机械类', '机械类'), ('物理类', '物理类'), ('化学类', '化学类'), ('生物类', '生物类')], default='请选择设备类型', max_length=10, verbose_name='设备类型'),
        ),
    ]
