# Generated by Django 2.0.7 on 2018-07-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180727_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eKind',
            field=models.CharField(choices=[('请选择设备类型：', '请选择设备类型'), ('计算机类', '计算机类'), ('机械类', '机械类'), ('物理类', '物理类'), ('化学类', '化学类'), ('生物类', '生物类'), ('其它类', '其它类')], default='请选择设备类型', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eState',
            field=models.CharField(choices=[('可借', '可借'), ('借出', '借出')], default='可借', max_length=3, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='借用学生'),
        ),
    ]
