# Generated by Django 2.0.7 on 2018-07-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180729_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usecount',
            new_name='useCount',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eKind',
            field=models.CharField(choices=[('计算机类', '计算机类'), ('机械类', '机械类'), ('物理类', '物理类'), ('化学类', '化学类'), ('生物类', '生物类'), ('其它类', '其它类')], default='请选择设备类型', max_length=10, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eStudent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='借用学生'),
        ),
        migrations.AddField(
            model_name='applylist',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Equipment', verbose_name='归还设备'),
        ),
        migrations.AddField(
            model_name='applylist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='归还学生'),
        ),
    ]
